# Generated by Django 4.2.4 on 2023-08-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="task_desccription",
            new_name="task_description",
        ),
    ]
