# Generated by Django 4.2.4 on 2023-08-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_task_desccription_task_task_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_status",
            field=models.CharField(
                choices=[("CL", "Completed"), ("PD", "Pending"), ("PR", "In progress")],
                default="PD",
                max_length=2,
            ),
        ),
    ]
